import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import BootstrapClient from './components/bootstrap-client'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}
